### ISSUE TITLE
✨ HttpStatusCode에 따른 ErrorCode 정의

### ISSUE THREAD

**Issue by uiurihappy** [depromeet/10mm-server#46]
## 📌 Description
- 점차 생성되는 API 명세 내용에 Fit한 ErrorCode 내용 정의
- RuntimeException을 상속받는 구조로 각 statusCode에 따른 Exception Class 구현

**Comment by uwoobeat** [comment]
@uiurihappy 

요거는 한번에 다 만드는 것보다 각 도메인 구현하면서 만드는 게 좋을 것 같은데 어떻게 생각하세요?
