### ISSUE TITLE
⚙️ Swagger Tag값에 넘버링

### ISSUE THREAD

**Issue by kdomo** [depromeet/10mm-server#96]
## 📌 Description
- 현재 Controller에 적용되어있는 `@Tag(name="미션")`과 같은 값들에 넘버링을 넣어주고 싶습니당
- operations-sorter: alpha 로 설정되어있어
`@Tag(name="1.[회원]")`
`@Tag(name="2.[미션]")`
`@Tag(name="3.[미션기록]")`
과 같이 적용되면 스웨거에서 보기 깔끔할 것 같아용
의견 부탁드립니당
@uiurihappy @uwoobeat

**Comment by uiurihappy** [comment]
넘버링을 정의하고 순서도 지정이 가능한가요??
순서가 ㄱㄴㄷ 처럼, 1,2,3 순으로 정렬되는 지 제가 몰라서요

**Comment by kdomo** [comment]
application.yml에
operations-sorter: alpha 설정이 되어있는데 숫자도 적용됨니당
